name: sidebar_widget
description: A customizable Flutter sidebar navigation package with support for nested navigation, animations, and hover effects.
version: 0.1.0
homepage: https://masteronevil.github.io/sidebar-widget/
repository: https://github.com/masteronevil/sidebar-widget


environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
